GET http://localhost:3000/users HTTP/1.1

###
GET http://localhost:3000/users/2 HTTP/1.1


###
POST http://localhost:3000/users HTTP/1.1
Content-Type: application/json

{
    "name": "David"
}

###
PUT http://localhost:3000/users/5 HTTP/1.1
Content-Type: application/json

{
    "name": "David2"
}

###
DELETE http://localhost:3000/users/4 HTTP/1.1