### Health
GET http://localhost:3000/ HTTP/1.1

### Listar usuarios
GET http://localhost:3000/users HTTP/1.1

### Crear usuario
POST http://localhost:3000/users HTTP/1.1
Content-Type: application/json

{
  "name": "Elmer",
  "email": "Elmer@funca.org"
}

### (Prueba duplicado: debe devolver 409)
POST http://localhost:3000/users HTTP/1.1
Content-Type: application/json

{
  "name": "Ana L",
  "email": "ana@funca.org"
}



# GET http://localhost:3000/users HTTP/1.1

# ###
# GET http://localhost:3000/users/2 HTTP/1.1


# ###
# POST http://localhost:3000/users HTTP/1.1
# Content-Type: application/json

# {
#     "name": "David"
# }

# ###
# PUT http://localhost:3000/users/5 HTTP/1.1
# Content-Type: application/json

# {
#     "name": "David2"
# }

# ###
# DELETE http://localhost:3000/users/4 HTTP/1.1